#ifndef INCLUDE_OPTIX_RENDERING_SYSTEM_FLOAT3_PROGRAM_H
#define INCLUDE_OPTIX_RENDERING_SYSTEM_FLOAT3_PROGRAM_H
namespace rt {

}	//	!namespace rt
#endif // !INCLUDE_OPTIX_RENDERING_SYSTEM_FLOAT3_PROGRAM_H

